### ISSUE TITLE
[BUG] - titel wordt 2x getoond in Safari

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-search-filter#52]
**Omschrijf het probleem**
data-vl-title wordt in Safari 2x getoond. In Chrome is het oké.

**Hoe te reproduceren**
Ga naar de demo pagina in Safari: https://webcomponenten.omgeving.vlaanderen.be/demo/vl-search-filter.html

**Gewenst gedrag**
Licht kort en duidelijk toe wat het gewenst gedragd is.

**Screenshots**
<img width="872" alt="Screenshot 2021-03-04 at 09 13 29" src="https://user-images.githubusercontent.com/8820456/109931985-e5c38980-7cc9-11eb-9764-151bb509777b.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Chrome | Safari
 - Versie Chrome = Version 88.0.4324.182 (Official Build) (x86_64)
 - Versie Safari = Version 14.0.2 (16610.3.7.1.9)
 - Versie component 3.1.7

**Comment by coemans** [comment]
Probleem is niet meer reproduceerbaar in de meest recente versie. Indien het alsnog een probleem blijkt, mag het issue opnieuw geopend worden.
